// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1585756869);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1585756989);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1585756629);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1585756749);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1585757109);
user_pref("browser.cache.disk.amount_written", 635);
user_pref("browser.cache.disk.capacity", 215040);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1585756873);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "68.4.1");
user_pref("extensions.lastPlatformVersion", "68.4.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"2d459b61-794e-4e39-956a-85ed2d64ea5e\",\"default-theme@mozilla.org\":\"9d635c0d-0300-47c5-86ed-de436a38aa45\"}");
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "d51d5cb3-7233-42f8-b2cb-80e1ab45b5b");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("security.sandbox.plugin.tempDirSuffix", "d58b4eb1-dc79-4383-a6af-94f482e53779");
user_pref("services.blocklist.pinning.checked", 1585756920);
user_pref("services.settings.clock_skew_seconds", -171);
user_pref("services.settings.last_etag", "\"1585730548574\"");
user_pref("services.settings.last_update_seconds", 1585756920);
user_pref("services.settings.main.hijack-blocklists.last_check", 1585756920);
user_pref("services.settings.main.language-dictionaries.last_check", 1585756920);
user_pref("services.settings.main.sites-classification.last_check", 1585756920);
user_pref("services.settings.security.onecrl.checked", 1585756920);
user_pref("toolkit.telemetry.cachedClientID", "f4ee7ff3-6baf-4f64-9335-88be7c9d5403");
